### ISSUE TITLE
Bumping version clears all previous yaml comments

### ISSUE THREAD

**Issue by tigermarques** [mbenabda/helm-local-chart-version#17]
Hi,

I'm using this plugin to bump a chart version, and event though it works as intended, it removes all comments that I have in the chart. Is there any way to prevent this?

Original file:
```yml
apiVersion: v2
name: testchart
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: 1.16.0
```

Modified file after plugin is executed:
```yml
apiVersion: v2
appVersion: 1.16.0
description: A Helm chart for Kubernetes
name: testchart
type: application
version: 0.1.1
```

Thank you!
